import type { OverlayConfig } from './types';
import { clean } from './helpers';

const makeRoadmap = (
  day30Title: string,
  day60Title: string,
  day90Title: string,
  day30: string[],
  day60: string[],
  day90: string[]
) => ({
  day30Title,
  day60Title,
  day90Title,
  day30,
  day60,
  day90,
});

export const PROFESSIONAL_SERVICES_OVERLAY: OverlayConfig = {
  key: 'professional_services',
  label: 'Professional Services',
  keywords: [
    'consulting',
    'consultant',
    'professional services',
    'advisory',
    'proposal',
    'proposals',
    'billable',
    'billable hours',
    'utilisation',
    'utilization',
    'retainer',
    'client delivery',
    'engagement',
    'fee leakage',
    'turnaround time',
    'service consistency',
    'capacity planning',
    'client economics',
    'legal',
    'accounting',
    'tax',
    'agency',
    'managed services',
    'sla',
    'matter management',
    'scope creep',
    'statement of work',
    'client mandate',
    'month-end',
    'campaign delivery',
    'support desk',
  ],
  narrative:
    'Professional services create advantage when the firm can distinguish advisory delivery, matter management, accounting administration, agency execution, technical project delivery, and managed-service SLA performance — while protecting utilisation, scope discipline, proposal conversion, and client economics.',
  recommendationBias: [
    'Segment the operating model by service line, because consulting, legal, accounting, agency, technical, and managed-service environments leak value in different ways.',
    'Treat proposal conversion, scoping discipline, utilisation, SLA performance, and client-retainer economics as one commercial control system.',
    'Install delivery governance that protects scope, turnaround, quality, client value, and margin before delivery pressure becomes fee leakage.',
  ],
  actionTemplates: [
    'Map the full commercial-to-delivery flow from lead source, proposal, scope definition, pricing, delivery handoff, utilisation, billing, and client retention.',
    'Classify the client workload into advisory engagements, matters, month-end/tax work, campaigns, technical projects, or SLA tickets to identify the true operating constraint.',
    'Create service-line dashboards covering pipeline quality, proposal conversion, scope drift, billable utilisation, delivery turnaround, write-offs, and account profitability.',
  ],
  riskHints: [
    'Generic professional-services management hides the real constraint; a law firm, accounting practice, agency, consultancy, and MSP require different control rhythms.',
    'Fee leakage usually enters through weak scope definition, under-priced work, ungoverned rework, poor utilisation, or uncontrolled client requests.',
    'Delivery inconsistency damages client trust, recurring revenue, referral quality, and future proposal conversion.',
  ],
  focusTags: [
    'Service-Line Segmentation',
    'Scope & Proposal Control',
    'Utilisation Governance',
    'Client Economics',
    'Delivery Reliability',
  ],
  roadmapBias: makeRoadmap(
    'Service-Line Diagnostic',
    'Commercial & Delivery Stabilisation',
    'Scalable Professional Services Model',
    [
      'Segment current work by service line: consulting/advisory, legal/matter work, accounting/tax, agency/campaign work, technical projects, or managed services.',
      'Quantify leakage across proposal conversion, scope creep, billable utilisation, write-offs, retainer under-recovery, SLA breach, and delayed billing.',
      'Create one executive view of pipeline quality, work-in-progress, staff capacity, client profitability, and delivery risk.',
    ],
    [
      'Install weekly governance for proposal approval, scope sign-off, delivery handoff, utilisation, client escalations, billing status, and account profitability.',
      'Clarify ownership between business development, account leadership, delivery teams, administration, and finance.',
      'Standardise templates for scoping, statements of work, change requests, recurring retainers, SLA reviews, and client outcome reporting.',
    ],
    [
      'Embed a repeatable operating rhythm that links pipeline health, service-line capacity, utilisation, delivery quality, billing discipline, and client retention.',
      'Build service-line playbooks for high-repeat work while preserving senior oversight on complex advisory or technical mandates.',
      'Position client economics, quality delivery, and disciplined scope control as the basis for profitable professional-services growth.',
    ]
  ),
};

export const INDUSTRY_OVERLAYS: Record<string, OverlayConfig> = {
  manufacturing: {
    key: 'manufacturing',
    label: 'Manufacturing',
    keywords: [
      'manufacturing',
      'factory',
      'production',
      'oee',
      'throughput',
      'scrap',
      'quality',
      'line speed',
      'downtime',
      'inventory',
      'bom',
      'routing',
      'changeover',
      'assembly',
      'work order',
      'batch',
      'recipe',
      'yield',
      'fmcg',
      'food safety',
      'traceability',
      'fabrication',
      'welding',
      'cnc',
      'maintenance',
      'breakdown',
      'raw material',
      'supplier delay',
      'stockout',
      'warehouse',
      'mrp',
    ],
    narrative:
      'Manufacturing advantage is created when leadership separates discrete production flow, batch/yield control, food/FMCG traceability, engineering and fabrication change control, maintenance reliability, supply-chain availability, product-margin protection, and factory throughput discipline.',
    recommendationBias: [
      'Treat manufacturing performance as an integrated system linking product margin, planning stability, material availability, OEE, quality, maintenance reliability, and working capital.',
      'Separate discrete work-order flow from batch/process yield, food/FMCG traceability, engineering fabrication, and maintenance reliability before recommending operational fixes.',
      'Use product-family margin, schedule adherence, first-pass quality, asset reliability, supplier performance, and inventory health as the core executive control levers.',
    ],
    actionTemplates: [
      'Build a margin and throughput view by product family, line, work centre, customer, plant, and production constraint.',
      'Classify the operating model into discrete assembly, process/batch production, food/FMCG, engineering fabrication, maintenance-intensive operations, or supply-chain-constrained flow.',
      'Stress-test BOM accuracy, routing discipline, MRP reliability, supplier lead time, first-pass yield, OEE, maintenance planning, and inventory health.',
    ],
    riskHints: [
      'Poor product mix, outdated standard costs, and weak pricing discipline can make high-volume production strategically unprofitable.',
      'A factory can appear busy while losing money through changeover loss, rework, batch variance, supplier disruption, poor OEE, or excess inventory.',
      'Weak BOM, routing, traceability, and engineering-change discipline converts operational complexity into quality failure and margin erosion.',
    ],
    focusTags: [
      'Product Margin Protection',
      'Factory Flow Control',
      'Yield & Quality Discipline',
      'Asset Reliability',
      'Material Availability',
      'Inventory Health',
    ],
    roadmapBias: makeRoadmap(
      'Factory Margin & Flow Diagnostic',
      'Control Recovery',
      'Disciplined Manufacturing System',
      [
        'Segment the operation by production model: discrete assembly, process/batch, food/FMCG, engineering fabrication, maintenance-intensive assets, or supply-chain-constrained production.',
        'Create one executive view of product margin, schedule adherence, OEE, first-pass yield, COPQ, material availability, inventory health, and maintenance reliability.',
        'Quantify the highest-value leakage pools across changeovers, batch variance, scrap, rework, downtime, supplier delay, and working-capital lock-up.',
      ],
      [
        'Intervene first on the product families, lines, work centres, suppliers, or assets carrying the greatest value at risk.',
        'Tighten planning discipline, MRP inputs, BOM/routing control, preventive maintenance, quality gates, and production accountability.',
        'Link factory-level recovery actions directly to gross margin, delivery reliability, and cash conversion impact.',
      ],
      [
        'Embed a manufacturing operating model that links product economics, schedule reliability, quality performance, OEE, inventory control, and asset reliability.',
        'Standardise daily, weekly, and monthly review rhythms across plants, lines, product families, and supply-chain constraints.',
        'Position disciplined manufacturing control as the foundation for durable margin quality, delivery performance, and scalable production growth.',
      ]
    ),
  },

  printing_packaging: {
    key: 'printing_packaging',
    label: 'Printing & Packaging',
    keywords: [
      'printing',
      'packaging',
      'press',
      'prepress',
      'pre-press',
      'finishing',
      'specification',
      'rerun',
      'setup time',
      'changeover',
      'waste',
      'artwork',
      'proof',
      'job ticket',
      'queue',
      'dispatch',
      'label',
      'labels',
      'flexo',
      'flexographic',
      'shrink sleeve',
      'sleeves',
      'film',
      'slitter',
      'rewinder',
      'carton',
      'folding carton',
      'corrugated',
      'folder gluer',
      'die-cutting',
      'commercial print',
      'litho',
      'digital print',
      'ctp',
      'new markets',
      'sales pipeline',
      'key accounts',
      'saa',
      'saa technical',
      'pharma',
      'freelance reps',
    ],
    narrative:
      'In printing and packaging, performance improves when leadership separates label and flexible-packaging flow, carton and post-press throughput, commercial print and pre-press control, market expansion, specification integrity, planning discipline, waste reduction, and capacity balance across press and finishing.',
    recommendationBias: [
      'Separate label/flexible packaging, carton/post-press, and commercial print workflows because each has different leakage points, bottlenecks, and quality risks.',
      'Treat margin leakage as a structured waterfall across quoting, absorbed customer changes, pre-press errors, make-ready waste, spoilage, reruns, finishing bottlenecks, and dispatch delay.',
      'Use right-first-time specification control, planning discipline, press/finishing capacity balance, and targeted market expansion as the key executive levers.',
    ],
    actionTemplates: [
      'Classify work by production stream: labels/flexible packaging, carton/folding carton, commercial print, pre-press/artwork control, or market-expansion pipeline.',
      'Build a job-level leakage view across quoting, artwork, proofing, stock, press, finishing, dispatch, customer changes, and reruns.',
      'Map the end-to-end flow from enquiry, quote, artwork, proof, job ticket, planning, press, finishing, dispatch, invoice, and customer feedback.',
    ],
    riskHints: [
      'Printing and packaging margins can be lost before production starts through weak quoting, unclear specifications, absorbed customer changes, or poor product/customer mix.',
      'Pre-press and artwork control failures create expensive downstream reruns, disputes, schedule disruption, and client trust damage.',
      'Finishing bottlenecks, poor sequencing, and rush-job disruption can make capacity appear constrained even when press utilisation looks healthy.',
    ],
    focusTags: [
      'Job Margin Waterfall',
      'Pre-Press & Specification Control',
      'Press / Finishing Balance',
      'Waste & Rerun Reduction',
      'Market Expansion',
    ],
    roadmapBias: makeRoadmap(
      'Job Margin & Flow Diagnostic',
      'Specification, Planning & Waste Control',
      'Disciplined Print/Packaging Operating Model',
      [
        'Segment current work by stream: labels/flexible packaging, carton/post-press, commercial print, pre-press/artwork, or growth-market pipeline.',
        'Quantify leakage by job, customer, press, finishing line, product type, rerun cause, make-ready waste, queue delay, and absorbed customer change.',
        'Create one executive dashboard for quoting discipline, artwork readiness, proof status, schedule attainment, waste, reruns, turnaround, and dispatch performance.',
      ],
      [
        'Install control gates for quote approval, artwork completeness, proof sign-off, job ticket accuracy, stock availability, and change-request discipline.',
        'Stabilise sequencing across pre-press, planning, press, finishing, and dispatch, with owner-led escalation on bottlenecks and rush-job disruption.',
        'Launch targeted commercial actions for profitable sectors such as pharma, food, cosmetics, aviation suppliers, industrial clients, or other high-fit accounts.',
      ],
      [
        'Embed a print/packaging operating rhythm that connects job economics, right-first-time execution, asset productivity, customer service, and sales pipeline quality.',
        'Standardise specifications, artwork governance, production release criteria, and post-job review loops across sites or production streams.',
        'Position disciplined turnaround, technical reliability, and targeted market expansion as the basis for sustainable packaging growth.',
      ]
    ),
  },

  construction: {
    key: 'construction',
    label: 'Construction',
    keywords: [
      'construction',
      'project',
      'variation',
      'claim',
      'site',
      'programme',
      'schedule',
      'cash flow',
      'boq',
      'certification',
      'retention',
      'subcontractor',
      'building contractor',
      'main contractor',
      'residential',
      'commercial building',
      'civil works',
      'civils',
      'earthworks',
      'roads',
      'stormwater',
      'bulk services',
      'specialist subcontractor',
      'electrical contractor',
      'plumbing',
      'hvac',
      'scaffolding',
      'safety file',
      'ohs',
      'risk assessment',
      'method statement',
      'quantity surveyor',
      'qs',
      'final account',
      'property development',
      'developer',
      'town planning',
      'facilities',
      'maintenance contractor',
      'work order',
      'sla',
    ],
    narrative:
      'Construction value is protected when leadership distinguishes building-contractor delivery, civil works, specialist subcontractor control, health and safety compliance, QS/cost governance, property-development feasibility, maintenance SLA work, programme discipline, commercial recovery, and project cash exposure.',
    recommendationBias: [
      'Segment the construction model first: general building contractor, civil works, specialist subcontractor, H&S compliance, QS/cost control, property development, project management, or facilities maintenance.',
      'Separate tender risk, contract administration, variation recovery, site productivity, subcontractor coordination, programme slippage, safety-file discipline, certification, and cash exposure.',
      'Use portfolio-level visibility to distinguish systemic margin pressure from isolated site, commercial, compliance, or cash-cycle failures.',
    ],
    actionTemplates: [
      'Build a project exposure view covering tender quality, contract status, variations, claims, programme position, site productivity, safety compliance, certification, retention, and cash peaks.',
      'Classify each project or service line by construction subtype so the right operating controls are applied to building, civils, subcontractor, compliance, QS, development, or maintenance work.',
      'Stress-test contract administration, notice compliance, claim substantiation, subcontractor coordination, safety-file completeness, programme governance, and payment certification.',
    ],
    riskHints: [
      'Construction margin is often lost through underpriced tenders, missed notices, weak variation recovery, poor subcontractor control, and delayed certification.',
      'A project can look operationally busy while programme slippage, safety non-compliance, claim weakness, and cash exposure are quietly compounding.',
      'Property development, civil works, specialist subcontracting, and maintenance/SLA work require different governance rhythms; one generic construction model will misdiagnose the issue.',
    ],
    focusTags: [
      'Subtype Delivery Control',
      'Commercial Recovery',
      'Programme Discipline',
      'Site Productivity',
      'Safety / Compliance',
      'Cash Exposure',
    ],
    roadmapBias: makeRoadmap(
      'Project/Subtype Exposure Diagnostic',
      'Commercial, Site & Compliance Control',
      'Predictable Construction Delivery Model',
      [
        'Segment active work by subtype: general building, civil works, specialist subcontracting, H&S compliance, QS/cost control, development management, or facilities maintenance.',
        'Quantify margin at risk across tender assumptions, BOQ gaps, variations, claims, site instructions, productivity loss, programme slippage, safety compliance gaps, and certification lag.',
        'Create one executive dashboard for project margin, programme status, variation recovery, subcontractor performance, safety-file readiness, certification, retention, and cash exposure.',
      ],
      [
        'Tighten contract administration, notice compliance, variation governance, safety-file discipline, weekly site controls, and payment-certification follow-up.',
        'Intervene on the projects, subcontractors, sites, or claims carrying the greatest value, compliance, or cash risk.',
        'Assign explicit ownership for programme recovery, commercial recovery, safety documentation, client approvals, and debtor/certification escalation.',
      ],
      [
        'Embed a construction operating model that links tender discipline, project execution, contract administration, safety compliance, commercial recovery, and liquidity control.',
        'Standardise project review rhythms by subtype so building, civils, subcontracting, development, and maintenance work are not governed with one blunt template.',
        'Position predictable delivery, audit-ready compliance, margin-accretive execution, and disciplined cash conversion as the standard for all construction work.',
      ]
    ),
  },

  agriculture: {
    key: 'agriculture',
    label: 'Agriculture',
    keywords: [
      'agriculture',
      'yield',
      'hectare',
      'crop',
      'weather',
      'farm',
      'input cost',
      'harvest',
      'irrigation',
      'livestock',
      'maize',
      'wheat',
      'soybean',
      'planting',
      'fertiliser',
      'fertilizer',
      'cattle',
      'sheep',
      'poultry',
      'dairy',
      'feed conversion',
      'fresh produce',
      'fruit',
      'vegetables',
      'packhouse',
      'grading',
      'cold chain',
      'borehole',
      'pivot',
      'drought',
      'agri-processing',
      'milling',
      'silo',
      'abattoir',
      'off-taker',
      'hedging',
      'seasonal cash',
    ],
    narrative:
      'Agricultural performance improves when leadership separates crop production, livestock productivity, fresh-produce packhouse flow, irrigation and water resilience, agri-processing throughput, enterprise mix, biological/weather risk, price realisation, and seasonal cash exposure.',
    recommendationBias: [
      'Treat farm value as an integrated system linking yield per hectare or animal, input efficiency, operational timing, water availability, biological risk, market realisation, and cash-cycle timing.',
      'Separate crop, livestock, fresh produce, irrigation, and agri-processing constraints before recommending operating interventions.',
      'Use enterprise mix, seasonal planning, risk layering, off-take discipline, working-capital headroom, and operational timeliness as the main executive levers.',
    ],
    actionTemplates: [
      'Segment the agricultural enterprise by crop, livestock, fresh produce, packhouse, irrigation/water, agri-processing, storage, and market-realisation flow.',
      'Build a seasonal margin and yield-gap view by farm, field, crop, herd/flock, packhouse line, or processing stream.',
      'Stress-test planting/harvest timing, input efficiency, water availability, animal health, post-harvest loss, storage, grading, off-take terms, hedging, and cash-cycle exposure.',
    ],
    riskHints: [
      'Agricultural under-performance is often misread if weather risk, biological risk, timing failure, input inefficiency, and market realisation are grouped together.',
      'Yield loss can be operational, biological, climatic, or market-driven; each requires a different management response.',
      'Seasonal cash exposure can become severe when input costs, storage delays, price realisation, insurance recovery, and off-taker payment timing move against the farm.',
    ],
    focusTags: [
      'Yield Realisation',
      'Enterprise Margin',
      'Water & Climate Resilience',
      'Biological Risk',
      'Post-Harvest / Packhouse Flow',
      'Seasonal Cash Exposure',
    ],
    roadmapBias: makeRoadmap(
      'Yield, Enterprise & Cash Diagnostic',
      'Seasonal Control Recovery',
      'Disciplined Agricultural Operating Model',
      [
        'Segment the business by enterprise: crop production, livestock, fresh produce/packhouse, irrigation/water, agri-processing, storage, or market realisation.',
        'Create one executive view of potential vs achieved yield, gross margin, input efficiency, water exposure, biological risk, post-harvest loss, and seasonal cash pressure.',
        'Quantify leakage across timing, labour, machinery, fertiliser/feed, water, disease/pest pressure, grading downgrades, storage loss, and price realisation.',
      ],
      [
        'Intervene on the farms, enterprises, operating windows, packhouse flows, herds/flocks, or water constraints carrying the greatest value at risk.',
        'Tighten seasonal planning, input control, irrigation scheduling, animal-health routines, off-take discipline, insurance logic, and cash-flow forecasting.',
        'Assign explicit accountability for field execution, packhouse performance, livestock productivity, water management, and market realisation.',
      ],
      [
        'Embed an agricultural operating model that links yield, enterprise margin, water resilience, biological risk, market realisation, and cash timing.',
        'Standardise seasonal review rhythms across farms, fields, enterprises, packhouses, or climatic zones where the portfolio requires it.',
        'Position disciplined agricultural control as the basis for resilient value creation, better funding confidence, and scalable farm performance.',
      ]
    ),
  },

  healthcare: {
    key: 'healthcare',
    label: 'Medical/Health Care',
    keywords: [
      'medical',
      'health',
      'healthcare',
      'patient',
      'clinical',
      'practice',
      'clinic',
      'hospital',
      'doctor',
      'nurse',
      'specialist',
      'pharmacy',
      'claims',
      'billing',
      'medical aid',
      'compliance',
      'patient administration',
      'appointment',
    ],
    narrative:
      'Healthcare performance strengthens when leadership balances patient care quality, clinical governance, operational flow, revenue-cycle discipline, and practical management visibility across the specific care setting being served.',
    recommendationBias: [
      'Separate patient-care quality, administrative workflow, revenue-cycle leakage, compliance exposure, and capacity utilisation so the right control system is improved first.',
      'Treat patient experience, documentation quality, appointment utilisation, claims discipline, and cash conversion as linked healthcare operating levers.',
      'Adapt the advisory response to the care setting, distinguishing private practices, clinics, hospitals, pharmacies, suppliers, and healthcare administration environments.',
    ],
    actionTemplates: [
      'Build one leadership view of patient flow, service quality, revenue-cycle performance, documentation completeness, and operating constraints.',
      'Map the end-to-end patient, claim, stock, or service workflow to identify where administrative friction, clinical handoff failure, or cash leakage is occurring.',
      'Strengthen role accountability across clinical staff, front-office administration, finance, stock control, compliance, and management reporting.',
    ],
    riskHints: [
      'Weak administrative workflow can pull clinical professionals into avoidable friction and reduce care capacity.',
      'Delayed claims, incomplete documentation, and poor billing follow-up can damage cash flow even when patient demand is healthy.',
      'Healthcare operating failure can erode patient trust, staff morale, compliance control, and economic performance at the same time.',
    ],
    focusTags: [
      'Patient Administration',
      'Clinical Governance',
      'Revenue Cycle Control',
      'Practice / Facility Operations',
      'Compliance Visibility',
    ],
    roadmapBias: makeRoadmap(
      'Healthcare Operating Diagnostic',
      'Workflow & Control Recovery',
      'Disciplined Care Operating Model',
      [
        'Separate patient-care quality, administrative workflow, revenue-cycle leakage, compliance exposure, and management visibility across the specific healthcare setting.',
        'Create one leadership view of patient flow, appointment utilisation, claims status, billing follow-up, documentation completeness, and operating risk.',
        'Quantify the highest-value leakage points across patient administration, claims, stock, staff workload, compliance, and cash conversion.',
      ],
      [
        'Tighten scheduling, documentation, billing, claims follow-up, stock control, and role accountability where operating friction is highest.',
        'Intervene on the workflows creating the greatest risk to patient experience, cash conversion, staff workload, or compliance control.',
        'Introduce weekly operating reviews that connect care quality, workflow discipline, revenue-cycle control, and management action.',
      ],
      [
        'Embed a healthcare operating model that links patient experience, workflow reliability, revenue-cycle discipline, compliance, and management reporting.',
        'Standardise review rhythms across practices, clinics, departments, sites, or service lines according to the client’s operating model.',
        'Position disciplined healthcare operations as the basis for better care, stronger trust, better cash flow, and sustainable capacity.',
      ]
    ),
  },

  energy: {
    key: 'energy',
    label: 'Energy',
    keywords: [
      'energy',
      'solar',
      'wind',
      'renewable',
      'ppa',
      'grid',
      'turbine',
      'module',
      'battery',
      'commissioning',
      'solar pv',
      'rooftop solar',
      'inverter',
      'panel',
      'epc',
      'installation',
      'dc string',
      'backup power',
      'bess',
      'storage',
      'generator',
      'genset',
      'loadshedding',
      'microgrid',
      'o&m',
      'performance ratio',
      'curtailment',
      'scada',
      'grid connection',
      'wheeling',
      'nersa',
      'permitting',
      'energy efficiency',
      'energy audit',
      'demand charge',
      'metering',
    ],
    narrative:
      'Energy value is protected when leadership separates solar EPC delivery, backup power and storage resilience, renewable asset operations, grid connection and permitting, demand-side efficiency, project IRR, contractual recovery, commissioning risk, and funding exposure.',
    recommendationBias: [
      'Segment the energy model by solar EPC, backup/storage, renewable asset operations, grid/permitting, energy efficiency, or project-finance exposure before defining recommendations.',
      'Treat IRR realisation as a layered outcome driven by resource quality, grid access, installation quality, commissioning discipline, curtailment, asset performance, contract structure, and funding control.',
      'Use delivery certainty, grid readiness, yield assurance, O&M effectiveness, warranty/claims recovery, and cash headroom as the main executive levers.',
    ],
    actionTemplates: [
      'Classify the energy opportunity or problem by subtype: solar EPC installation, backup power/storage, renewable asset operations, grid/permitting, energy efficiency, or project finance.',
      'Build a project and asset view covering margin, IRR at risk, schedule slippage, grid dependency, commissioning status, curtailment, O&M cost, warranty exposure, and funding headroom.',
      'Stress-test site design, installation quality, grid approval, commissioning readiness, PPA/offtake quality, tariff assumptions, asset monitoring, and claims recovery.',
    ],
    riskHints: [
      'Energy projects can look commercially attractive while hidden grid, commissioning, curtailment, warranty, or O&M risks erode return realisation.',
      'Solar EPC and backup-power work require strong installation, commissioning, procurement, and handover discipline; asset portfolios require yield and O&M governance.',
      'Grid-connection delays, weak payment security, poor warranty recovery, and underestimated funding needs can turn technically sound projects into cash-stress cases.',
    ],
    focusTags: [
      'Solar / EPC Delivery',
      'Backup & Storage Resilience',
      'Grid Readiness',
      'Asset Yield Assurance',
      'IRR Realisation',
      'Funding Exposure',
    ],
    roadmapBias: makeRoadmap(
      'Energy Subtype & Economics Diagnostic',
      'Delivery, Grid & Asset Control',
      'Disciplined Energy Portfolio Model',
      [
        'Segment the work by subtype: solar EPC, backup/storage, renewable asset operations, grid/permitting, energy efficiency, or project-finance exposure.',
        'Create one executive view of IRR at risk, margin, schedule slippage, grid approval, commissioning status, curtailment, O&M risk, warranty exposure, and cash headroom.',
        'Quantify the highest-value leakage pools across design assumptions, procurement, installation, grid delay, commissioning gaps, asset underperformance, and funding pressure.',
      ],
      [
        'Intervene on the projects, installations, grid dependencies, or assets carrying the greatest economic, delivery, or cash risk.',
        'Tighten governance over EPC delivery, supplier readiness, installation QA, commissioning, grid interface, claims recovery, and payment-security discipline.',
        'Link technical progress, asset yield, contractual recovery, and cash exposure into one weekly executive review rhythm.',
      ],
      [
        'Embed an energy operating model that links project economics, delivery control, grid readiness, contractual performance, asset yield, and long-term cash generation.',
        'Standardise review rhythms across solar, storage, efficiency, renewable assets, and grid-dependent projects according to lifecycle stage.',
        'Position disciplined energy-portfolio control as the basis of resilient return realisation and scalable energy-sector growth.',
      ]
    ),
  },

  general: {
    key: 'general',
    label: 'General Business',
    keywords: [],
    narrative:
      'The advisory response must translate the stated challenge into a high-impact, owner-led execution plan that delivers measurable strategic and financial outcomes.',
    recommendationBias: [],
    actionTemplates: [],
    riskHints: [],
    focusTags: [],
    roadmapBias: makeRoadmap('Rapid Diagnostic & Containment', 'Execution Stabilisation', 'Institutionalised Discipline', [], [], []),
  },
};

export function resolveOverlayKey(industry: string): string {
  const industryClean = clean(industry).toLowerCase();

  const industryKeyMap: Record<string, string> = {
    'professional services': 'professional_services',
    consulting: 'professional_services',
    consultancy: 'professional_services',
    advisory: 'professional_services',
    'law firm': 'professional_services',
    accounting: 'professional_services',
    agency: 'professional_services',
    'managed services': 'professional_services',

    manufacturing: 'manufacturing',
    factory: 'manufacturing',
    production: 'manufacturing',
    'food manufacturing': 'manufacturing',
    fabrication: 'manufacturing',

    'printing/packaging': 'printing_packaging',
    'printing & packaging': 'printing_packaging',
    printing: 'printing_packaging',
    packaging: 'printing_packaging',
    labels: 'printing_packaging',
    'commercial print': 'printing_packaging',

    construction: 'construction',
    building: 'construction',
    contractor: 'construction',
    civils: 'construction',
    'civil works': 'construction',
    subcontractor: 'construction',
    'property development': 'construction',
    'facilities maintenance': 'construction',

    agriculture: 'agriculture',
    farming: 'agriculture',
    farm: 'agriculture',
    crop: 'agriculture',
    livestock: 'agriculture',
    packhouse: 'agriculture',

    'medical/health care': 'healthcare',
    'medical / health care': 'healthcare',
    healthcare: 'healthcare',
    health: 'healthcare',
    medical: 'healthcare',
    clinic: 'healthcare',
    hospital: 'healthcare',
    pharmacy: 'healthcare',
    'private practice': 'healthcare',

    energy: 'energy',
    solar: 'energy',
    renewable: 'energy',
    renewables: 'energy',
    battery: 'energy',
    'backup power': 'energy',
    'energy efficiency': 'energy',
  };

  for (const [pattern, key] of Object.entries(industryKeyMap)) {
    if (industryClean.includes(pattern)) return key;
  }

  return 'general';
}

export function resolveOverlay(industry: string): OverlayConfig {
  const key = resolveOverlayKey(industry);
  if (key === 'professional_services') return PROFESSIONAL_SERVICES_OVERLAY;
  return INDUSTRY_OVERLAYS[key] || INDUSTRY_OVERLAYS.general;
}
