import { useEffect, useMemo, useState } from 'react';
import NexusShell from '@/components/NexusShell';
import { TrendingUp, TrendingDown, DollarSign, Users, BarChart2, Activity, Target, Briefcase } from 'lucide-react';

type SupabaseClientLike = any;
type GenericRow = Record<string, any>;

type Snapshot = {
  advisoryOutputsTotal: number;
  activeClientsTotal: number;
  avgProjectVelocity: number;
  highUrgencyTotal: number;
  estimatedValueTotal: number;
  overdueActionsTotal: number;
  blockedActionsTotal: number;
  openActionsTotal: number;
  completedActionsTotal: number;
  avgActionAgeDays: number;
  monthlyAdvisoryOutputs: { label: string; value: number }[];
  monthlyEstimatedValue: { label: string; value: number }[];
  monthlyProjectVelocity: number[];
  monthlyHighUrgency: { label: string; value: number }[];
  monthlyActionClosures: { label: string; value: number }[];
  industryMix: { label: string; value: number; color: string }[];
  categoryMix: { label: string; value: number; color: string }[];
  ownerLoad: { label: string; value: number; color: string }[];
  healthMix: { label: string; value: number; color: string }[];
};

const SUPABASE_URL = import.meta.env.VITE_NEXUS_SUPABASE_URL || 'https://clwjhdxjdpikrxcormsb.supabase.co';
const SUPABASE_ANON_KEY = import.meta.env.VITE_NEXUS_SUPABASE_ANON_KEY || 'sb_publishable_EJGKO-RRnc9zJo8jUxsLlQ_uvTNC2Bw';
let supabasePromise: Promise<SupabaseClientLike> | null = null;

function clean(v: unknown) { return String(v || '').trim(); }
function parseNum(v: unknown) { const n = Number(String(v ?? '').replace(/[^0-9.-]+/g, '')); return Number.isFinite(n) ? n : 0; }
function urgency(v: unknown) { const r = clean(v).toLowerCase(); if (r === 'critical' || r === 'very high') return 'Critical'; if (r === 'high' || r === 'urgent') return 'High'; if (r === 'low') return 'Low'; return 'Medium'; }
function monthKey(d: Date) { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; }
function monthBuckets(n=7){const now=new Date(); return Array.from({length:n}).map((_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-(n-1-i),1); return {key:monthKey(d),label:d.toLocaleString('en-GB',{month:'short'})};});}
function color(i:number){return ['#2563eb','#7c3aed','#0891b2','#059669','#d97706','#60a5fa'][i%6];}
function deriveCategory(title:string,fallback='Advisory'){const t=clean(title); return t ? t.replace(/\s+Strategic Review$/i,'').replace(/\s+Review$/i,'').replace(/^.+?\s+/,'') || fallback : fallback;}
function daysSince(value: unknown){const d=new Date(clean(value)); return Number.isNaN(d.getTime())?0:Math.max(0,Math.floor((Date.now()-d.getTime())/86400000));}
function isOverdue(due:unknown,status:unknown){const s=clean(status).toLowerCase(); if(['completed','done','complete'].includes(s)) return false; const d=new Date(clean(due)); if(Number.isNaN(d.getTime())) return false; const t=new Date(); t.setHours(0,0,0,0); d.setHours(0,0,0,0); return d.getTime()<t.getTime();}
async function getSupabase(){ const existing=(window as Window & {__nexusSupabase?: SupabaseClientLike}).__nexusSupabase; if(existing) return existing; if(!supabasePromise){ supabasePromise=import(/* @vite-ignore */'https://esm.sh/@supabase/supabase-js@2').then((mod:any)=>{const c=mod.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}); (window as Window & {__nexusSupabase?: SupabaseClientLike}).__nexusSupabase=c; return c;}); } return supabasePromise; }
async function getOrgId(){const s=await getSupabase(); const {data,error}=await s.auth.getSession(); if(error) throw new Error(error.message); const id=data?.session?.user?.id; if(!id) throw new Error('No authenticated user session found.'); const p=await s.from('profiles').select('organisation_id').eq('id',id).maybeSingle(); if(p.error) throw new Error(p.error.message); return clean(p.data?.organisation_id);}

function BarChart({ data, color='#2563eb', height=80 }: { data:{label:string;value:number}[]; color?:string; height?:number }) {
  const max=Math.max(...data.map(d=>d.value),1); return <div style={{display:'flex',alignItems:'flex-end',gap:'6px',height:`${height+20}px`}}>{data.map((d,i)=>{const h=Math.round((d.value/max)*height); return <div key={i} style={{flex:1,display:'flex',flexDirection:'column',alignItems:'center',gap:'4px'}}><div style={{width:'100%',height:`${height}px`,display:'flex',alignItems:'flex-end'}}><div style={{width:'100%',height:`${h}px`,background:`linear-gradient(180deg, ${color} 0%, ${color}88 100%)`,borderRadius:'4px 4px 0 0'}} /></div><span style={{fontSize:'0.58rem',color:'#94a3b8',whiteSpace:'nowrap'}}>{d.label}</span></div>;})}</div>;
}
function LineChart({ data, color='#3b82f6', height=80 }: { data:number[]; color?:string; height?:number }) {
  const safe=data.length?data:[0,0,0,0,0,0,0]; const max=Math.max(...safe,1); const min=Math.min(...safe); const range=max-min||1; const w=280,h=height; const pts=safe.map((v,i)=>`${(i/(safe.length-1||1))*w},${h-((v-min)/range)*(h-10)-5}`); return <svg width='100%' viewBox={`0 0 ${w} ${h}`} style={{overflow:'visible'}}><defs><linearGradient id={`g-${color.replace('#','')}`} x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stopColor={color} stopOpacity='0.3'/><stop offset='100%' stopColor={color} stopOpacity='0.02'/></linearGradient></defs><path d={`M${pts[0]} L${pts.join(' L')} L${w},${h} L0,${h} Z`} fill={`url(#g-${color.replace('#','')})`} /><path d={`M${pts[0]} L${pts.join(' L')}`} fill='none' stroke={color} strokeWidth='2' />{safe.map((v,i)=>{const x=(i/(safe.length-1||1))*w; const y=h-((v-min)/range)*(h-10)-5; return <circle key={i} cx={x} cy={y} r='3' fill={color}/>;})}</svg>;
}
function DonutChart({ segments, size=100 }: { segments:{label:string;value:number;color:string}[]; size?:number }) {
  const safe=segments.length?segments:[{label:'No Data',value:1,color:'#1e3a5f'}]; const total=safe.reduce((s,d)=>s+d.value,0); const r=38,cx=50,cy=50; let cum=0; const paths=safe.map(seg=>{const pct=seg.value/total; const start=cum*2*Math.PI-Math.PI/2; const end=(cum+pct)*2*Math.PI-Math.PI/2; cum+=pct; const x1=cx+r*Math.cos(start),y1=cy+r*Math.sin(start),x2=cx+r*Math.cos(end),y2=cy+r*Math.sin(end); return {d:`M ${cx} ${cy} L ${x1} ${y1} A ${r} ${r} 0 ${pct>0.5?1:0} 1 ${x2} ${y2} Z`,...seg};}); return <div style={{display:'flex',alignItems:'center',gap:'1rem'}}><svg width={size} height={size} viewBox='0 0 100 100'>{paths.map((p,i)=><path key={i} d={p.d} fill={p.color} stroke='#0a0f1e' strokeWidth='1.5' />)}<circle cx={cx} cy={cy} r='22' fill='#0d1526'/></svg><div style={{display:'flex',flexDirection:'column',gap:'0.35rem',width:'100%'}}>{safe.map(s=><div key={s.label} style={{display:'flex',alignItems:'center',gap:'0.4rem'}}><div style={{width:'8px',height:'8px',borderRadius:'2px',background:s.color}}/><span style={{fontSize:'0.68rem',color:'#94a3b8'}}>{s.label}</span><span style={{fontSize:'0.68rem',color:'#e2e8f0',fontWeight:600,marginLeft:'auto'}}>{Math.round((s.value/total)*100)}%</span></div>)}</div></div>;
}
function GaugeChart({ value, max=100, color='#2563eb' }: { value:number; max?:number; color?:string }) { const pct=Math.max(0,Math.min(value/max,1)); const angle=pct*180-90; const r=38,cx=50,cy=50; const endX=cx+r*Math.cos((angle*Math.PI)/180), endY=cy+r*Math.sin((angle*Math.PI)/180); return <div style={{textAlign:'center'}}><svg width='100%' viewBox='0 0 100 60'><path d={`M ${cx-r} ${cy} A ${r} ${r} 0 0 1 ${cx+r} ${cy}`} fill='none' stroke='#1e3a5f' strokeWidth='8'/><path d={`M ${cx-r} ${cy} A ${r} ${r} 0 ${pct>0.5?1:0} 1 ${endX} ${endY}`} fill='none' stroke={color} strokeWidth='8'/><text x='50' y='48' textAnchor='middle' fill='#e2e8f0' fontSize='12' fontWeight='700'>{Math.round(value)}%</text></svg></div>; }

const empty: Snapshot = { advisoryOutputsTotal:0,activeClientsTotal:0,avgProjectVelocity:0,highUrgencyTotal:0,estimatedValueTotal:0,overdueActionsTotal:0,blockedActionsTotal:0,openActionsTotal:0,completedActionsTotal:0,avgActionAgeDays:0,monthlyAdvisoryOutputs:monthBuckets().map(b=>({label:b.label,value:0})),monthlyEstimatedValue:monthBuckets().map(b=>({label:b.label,value:0})),monthlyProjectVelocity:[0,0,0,0,0,0,0],monthlyHighUrgency:monthBuckets().map(b=>({label:b.label,value:0})),monthlyActionClosures:monthBuckets().map(b=>({label:b.label,value:0})),industryMix:[],categoryMix:[],ownerLoad:[],healthMix:[] };

export default function AnalyticsPage(){
  const [snapshot,setSnapshot]=useState<Snapshot>(empty); const [hoveredCard,setHoveredCard]=useState<string|null>(null); const [loadError,setLoadError]=useState(''); const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true; (async()=>{try{setLoading(true); const orgId=await getOrgId(); const s=await getSupabase(); const [adv,reports,projects,actions]=await Promise.all([s.from('advisory_inputs').select('*').eq('organisation_id',orgId), s.from('reports').select('*').eq('organisation_id',orgId), s.from('projects').select('*').eq('organisation_id',orgId), s.from('project_actions').select('*').eq('organisation_id',orgId)]); if(adv.error||reports.error||projects.error||actions.error) throw new Error(adv.error?.message||reports.error?.message||projects.error?.message||actions.error?.message||'Could not load analytics.'); const advisory=adv.data||[]; const rRows=reports.data||[]; const pRows=projects.data||[]; const aRows=actions.data||[]; const buckets=monthBuckets(); const out=new Map(buckets.map(b=>[b.key,0])); const value=new Map(buckets.map(b=>[b.key,0])); const high=new Map(buckets.map(b=>[b.key,0])); const velocity=new Map(buckets.map(b=>[b.key,0])); const closures=new Map(buckets.map(b=>[b.key,0])); const industry=new Map<string,number>(); const category=new Map<string,number>(); const owners=new Map<string,number>(); const health=new Map([['Healthy',0],['Watch',0],['At Risk',0]]); const clients=new Set<string>(); for(const row of advisory){clients.add(clean(row.client_name).toLowerCase()); const d=new Date(clean(row.created_at||row.date)); const k=Number.isNaN(d.getTime())?'':monthKey(d); if(k&&out.has(k)){out.set(k,(out.get(k)||0)+1); value.set(k,(value.get(k)||0)+parseNum(row.estimated_value)); const u=urgency(row.urgency_level); if(u==='High'||u==='Critical') high.set(k,(high.get(k)||0)+1);} const ind=clean(row.industry||'Unclassified'); industry.set(ind,(industry.get(ind)||0)+1);} for(const row of rRows){const c=deriveCategory(clean(row.title),'Advisory'); category.set(c,(category.get(c)||0)+1);} let overdue=0,blocked=0,completed=0; const actionsByProject=new Map<string, GenericRow[]>(); for(const a of aRows){const pid=clean(a.project_id); if(!actionsByProject.has(pid)) actionsByProject.set(pid,[]); actionsByProject.get(pid)!.push(a); const owner=clean(a.owner_name||'Unassigned'); owners.set(owner,(owners.get(owner)||0)+1); const d=new Date(clean(a.updated_at||a.created_at)); const k=Number.isNaN(d.getTime())?'':monthKey(d); const st=clean(a.status).toLowerCase(); if(k&&velocity.has(k)&&['completed','in_progress','active','working'].includes(st)) velocity.set(k,(velocity.get(k)||0)+1); if(k&&closures.has(k)&&['completed','done','complete'].includes(st)) closures.set(k,(closures.get(k)||0)+1); if(isOverdue(a.due_date,a.status)) overdue++; if(['blocked','on_hold','on hold'].includes(st)) blocked++; if(['completed','done','complete'].includes(st)) completed++; }
          for(const p of pRows){const acts=actionsByProject.get(clean(p.id))||[]; const total=acts.length||1; const done=acts.filter(a=>['completed','done','complete'].includes(clean(a.status).toLowerCase())).length; const b=acts.filter(a=>['blocked','on_hold','on hold'].includes(clean(a.status).toLowerCase())).length; const o=acts.filter(a=>isOverdue(a.due_date,a.status)).length; let score=50+Math.round((done/total)*40)-b*18-o*12; if(clean(p.status).toLowerCase()==='completed') score=100; score=Math.max(0,Math.min(100,score)); const label=score>=80?'Healthy':score>=55?'Watch':'At Risk'; health.set(label,(health.get(label)||0)+1); }
          const next:Snapshot={ advisoryOutputsTotal:advisory.length, activeClientsTotal:[...clients].filter(Boolean).length, avgProjectVelocity:Number((Array.from(velocity.values()).reduce((a,b)=>a+b,0)/buckets.length).toFixed(1)), highUrgencyTotal: advisory.filter(r=>['High','Critical'].includes(urgency(r.urgency_level))).length, estimatedValueTotal: advisory.reduce((s,row)=>s+parseNum(row.estimated_value),0), overdueActionsTotal: overdue, blockedActionsTotal: blocked, completedActionsTotal: completed, openActionsTotal: aRows.length-completed, avgActionAgeDays: aRows.length?Math.round(aRows.reduce((s,a)=>s+daysSince(a.created_at||a.updated_at),0)/aRows.length):0, monthlyAdvisoryOutputs:buckets.map(b=>({label:b.label,value:out.get(b.key)||0})), monthlyEstimatedValue:buckets.map(b=>({label:b.label,value:Number(((value.get(b.key)||0)/1000000).toFixed(2))})), monthlyProjectVelocity:buckets.map(b=>velocity.get(b.key)||0), monthlyHighUrgency:buckets.map(b=>({label:b.label,value:high.get(b.key)||0})), monthlyActionClosures:buckets.map(b=>({label:b.label,value:closures.get(b.key)||0})), industryMix:[...industry.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([label,v],i)=>({label,value:v,color:color(i)})), categoryMix:[...category.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([label,v],i)=>({label,value:v,color:color(i)})), ownerLoad:[...owners.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([label,v],i)=>({label,value:v,color:color(i)})), healthMix:['Healthy','Watch','At Risk'].map((label,i)=>({label,value:health.get(label)||0,color:['#22c55e','#f59e0b','#ef4444'][i]})), }; if(active){setSnapshot(next); setLoadError('');}}catch(e:any){if(active){setSnapshot(empty); setLoadError(e?.message||'Could not load analytics.');}}finally{if(active)setLoading(false);}})(); return ()=>{active=false};},[]);

  const monthLabels=snapshot.monthlyAdvisoryOutputs.map(i=>i.label); const latestOutput=snapshot.monthlyAdvisoryOutputs.at(-1)?.value||0; const prevOutput=snapshot.monthlyAdvisoryOutputs.at(-2)?.value||0; const latestValue=snapshot.monthlyEstimatedValue.at(-1)?.value||0; const prevValue=snapshot.monthlyEstimatedValue.at(-2)?.value||0;
  const outputDelta = prevOutput<=0 ? (latestOutput>0?`+${latestOutput} vs prior month`:'No monthly change') : `${(((latestOutput-prevOutput)/prevOutput)*100)>=0?'+':''}${(((latestOutput-prevOutput)/prevOutput)*100).toFixed(0)}% MoM`;
  const valueDelta = prevValue<=0 ? (latestValue>0?`+R ${latestValue.toFixed(2)}M this month`:'No monthly change') : `${(((latestValue-prevValue)/prevValue)*100)>=0?'+':''}${(((latestValue-prevValue)/prevValue)*100).toFixed(0)}% MoM`;
  const actionCompletionRate=snapshot.completedActionsTotal+snapshot.openActionsTotal>0?Math.round((snapshot.completedActionsTotal/(snapshot.completedActionsTotal+snapshot.openActionsTotal))*100):0;
  const gaugeData=[ {label:'Advisory Output Quality', value:Math.min(snapshot.advisoryOutputsTotal>0?60+snapshot.advisoryOutputsTotal*5:0,100), color:'#2563eb'}, {label:'Execution Momentum', value:Math.min(snapshot.avgProjectVelocity*18,100), color:'#f59e0b'}, {label:'Urgency Control', value:Math.max(0,Math.min(snapshot.advisoryOutputsTotal>0?((snapshot.advisoryOutputsTotal-snapshot.highUrgencyTotal)/snapshot.advisoryOutputsTotal)*100:0,100)), color:'#22c55e'}, {label:'Execution Discipline', value:Math.max(0,Math.min(100-snapshot.overdueActionsTotal*12-snapshot.blockedActionsTotal*10+actionCompletionRate,100)), color:'#7c3aed'}];
  const cardStyle=(id:string):React.CSSProperties=>({background:'#0d1526',border:`1px solid ${hoveredCard===id?'#3b82f6':'#1e3a5f'}`,borderLeft:`3px solid ${hoveredCard===id?'#3b82f6':'#2563eb'}`,borderRadius:'10px',padding:'1.5rem',transition:'all 0.2s ease',transform:hoveredCard===id?'translateY(-3px)':'translateY(0)',boxShadow:hoveredCard===id?'0 8px 32px rgba(37,99,235,0.2)':'0 2px 8px rgba(0,0,0,0.3)',cursor:'default'});
  const panel:React.CSSProperties={background:'#0d1526',border:'1px solid #1e3a5f',borderRadius:'12px',padding:'1.75rem'}; const kicker=(t:string)=><div style={{fontSize:'0.6rem',letterSpacing:'0.2em',color:'#3b82f6',textTransform:'uppercase' as const,fontWeight:'600',marginBottom:'0.2rem'}}>{t}</div>; const delta=(val:string,up:boolean)=><span style={{display:'inline-flex',alignItems:'center',gap:'0.2rem',fontSize:'0.7rem',fontWeight:'600',color:up?'#22c55e':'#ef4444'}}>{up?<TrendingUp size={11}/>:<TrendingDown size={11}/>} {val}</span>;
  const scorecardRows=[ {area:'Estimated Value Pipeline', status:snapshot.estimatedValueTotal>0?'Active':'Build', value:`R ${(snapshot.estimatedValueTotal/1000000).toFixed(2)}M captured`, icon:DollarSign, color:snapshot.estimatedValueTotal>0?'#22c55e':'#f59e0b'}, {area:'Client Portfolio Expansion', status:snapshot.activeClientsTotal>0?'On Track':'Build', value:`${snapshot.activeClientsTotal} active clients`, icon:Users, color:snapshot.activeClientsTotal>0?'#22c55e':'#f59e0b'}, {area:'Action Closure Trend', status:snapshot.monthlyActionClosures.at(-1)?.value ? 'Active' : 'Build', value:`${snapshot.monthlyActionClosures.at(-1)?.value||0} closed this month`, icon:Target, color:(snapshot.monthlyActionClosures.at(-1)?.value||0)>0?'#22c55e':'#64748b'}, {area:'Execution Backlog', status:snapshot.overdueActionsTotal===0?'Controlled':snapshot.overdueActionsTotal<3?'Watch':'At Risk', value:`${snapshot.overdueActionsTotal} overdue / ${snapshot.blockedActionsTotal} blocked`, icon:Briefcase, color:snapshot.overdueActionsTotal===0?'#22c55e':snapshot.overdueActionsTotal<3?'#f59e0b':'#ef4444'}, {area:'Action Ageing', status:snapshot.avgActionAgeDays<=7?'Fresh':snapshot.avgActionAgeDays<=14?'Watch':'Old', value:`${snapshot.avgActionAgeDays}d average age`, icon:Activity, color:snapshot.avgActionAgeDays<=7?'#22c55e':snapshot.avgActionAgeDays<=14?'#f59e0b':'#ef4444'}, {area:'Industry Coverage', status:snapshot.industryMix.length>1?'Diversifying':'Concentrated', value:`${snapshot.industryMix.length} industries represented`, icon:TrendingUp, color:snapshot.industryMix.length>1?'#22c55e':'#f59e0b'} ];

  return <NexusShell><div style={{padding:'1.5rem 2rem 3rem'}}>
    <div style={{marginBottom:'1.75rem'}}><div onMouseEnter={()=>setHoveredCard('hero')} onMouseLeave={()=>setHoveredCard(null)} style={{background:'linear-gradient(135deg, #0d1526 0%, #0f1e3a 100%)',border:`1px solid ${hoveredCard==='hero'?'#3b82f6':'#1e3a5f'}`,borderLeft:'3px solid #2563eb',borderRadius:'12px',padding:'1.5rem 2rem',transition:'all 0.2s ease',transform:hoveredCard==='hero'?'translateY(-4px)':'translateY(0)',boxShadow:hoveredCard==='hero'?'0 8px 32px rgba(37,99,235,0.2)':'0 2px 8px rgba(0,0,0,0.3)'}}><div style={{fontSize:'0.6rem',letterSpacing:'0.25em',color:'#3b82f6',textTransform:'uppercase',fontWeight:'600',marginBottom:'0.4rem'}}>Executive Intelligence Layer</div><h1 style={{margin:'0 0 0.5rem',fontSize:'1.5rem',fontWeight:'800',color:'#e2e8f0'}}>NEXUS Analytics</h1><p style={{margin:0,color:'#94a3b8',fontSize:'0.85rem',lineHeight:'1.6',maxWidth:'680px'}}>Board-level performance intelligence across advisory output, project velocity, client portfolio health, and financial operating metrics.</p>{loadError?<div style={{marginTop:'0.75rem',color:'#f59e0b',fontSize:'0.75rem'}}>{loadError}</div>:null}{!loadError&&loading?<div style={{marginTop:'0.75rem',color:'#94a3b8',fontSize:'0.75rem'}}>Loading live organisation analytics…</div>:null}</div></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(4, 1fr)',gap:'1.25rem',marginBottom:'1.5rem'}}>{[{label:'Estimated Value (ZAR M)',value:`R ${(snapshot.estimatedValueTotal/1000000).toFixed(2)}M`,delta:valueDelta,up:latestValue>=prevValue,icon:DollarSign,id:'k1'},{label:'Active Clients',value:`${snapshot.activeClientsTotal}`,delta:`${snapshot.industryMix.length} industries`,up:snapshot.activeClientsTotal>0,icon:Users,id:'k2'},{label:'Advisory Outputs',value:`${snapshot.advisoryOutputsTotal}`,delta:outputDelta,up:latestOutput>=prevOutput,icon:BarChart2,id:'k3'},{label:'Avg Project Velocity',value:`${snapshot.avgProjectVelocity.toFixed(1)}/mo`,delta:`${snapshot.overdueActionsTotal} overdue / ${snapshot.blockedActionsTotal} blocked`,up:snapshot.overdueActionsTotal===0&&snapshot.blockedActionsTotal===0,icon:Activity,id:'k4'}].map(({label,value,delta:d,up,icon:Icon,id})=><div key={id} onMouseEnter={()=>setHoveredCard(id)} onMouseLeave={()=>setHoveredCard(null)} style={cardStyle(id)}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:'0.875rem'}}><div style={{fontSize:'0.68rem',color:'#94a3b8',textTransform:'uppercase',letterSpacing:'0.08em'}}>{label}</div><Icon size={14} color='#2563eb'/></div><div style={{fontSize:'1.75rem',fontWeight:'700',color:'#60a5fa',lineHeight:1,marginBottom:'0.4rem'}}>{value}</div>{delta(d,up)}</div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1.25rem',marginBottom:'1.5rem'}}><div style={panel}>{kicker('CFO View')}<h3 style={{margin:'0 0 0.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Estimated Value Trend (ZAR M)</h3><div style={{fontSize:'0.72rem',color:'#94a3b8',marginBottom:'1.25rem'}}>Monthly estimated value captured from advisory inputs — last 7 months</div><BarChart data={snapshot.monthlyEstimatedValue} color='#2563eb' height={90}/></div><div style={panel}>{kicker('CEO View')}<h3 style={{margin:'0 0 0.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Advisory Output Volume</h3><div style={{fontSize:'0.72rem',color:'#94a3b8',marginBottom:'1.25rem'}}>Number of advisory outputs generated per month</div><BarChart data={snapshot.monthlyAdvisoryOutputs} color='#7c3aed' height={90}/></div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1.25rem',marginBottom:'1.5rem'}}><div style={panel}>{kicker('CEO View')}<h3 style={{margin:'0 0 0.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Advisory Output Trend</h3><div style={{fontSize:'0.72rem',color:'#94a3b8',marginBottom:'1rem'}}>Rolling 7-month output pattern</div><LineChart data={snapshot.monthlyAdvisoryOutputs.map(i=>i.value)} color='#22c55e' height={80}/><div style={{display:'flex',justifyContent:'space-between',marginTop:'0.75rem'}}>{monthLabels.map(m=><span key={m} style={{fontSize:'0.58rem',color:'#94a3b8'}}>{m}</span>)}</div></div><div style={panel}>{kicker('COO View')}<h3 style={{margin:'0 0 0.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Project Velocity (per month)</h3><div style={{fontSize:'0.72rem',color:'#94a3b8',marginBottom:'1rem'}}>Projects completed or advanced per month</div><LineChart data={snapshot.monthlyProjectVelocity} color='#f59e0b' height={80}/><div style={{display:'flex',justifyContent:'space-between',marginTop:'0.75rem'}}>{monthLabels.map(m=><span key={m} style={{fontSize:'0.58rem',color:'#94a3b8'}}>{m}</span>)}</div></div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'1.25rem',marginBottom:'1.5rem'}}><div style={panel}>{kicker('CEO View')}<h3 style={{margin:'0 0 1.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Portfolio Mix by Category</h3><DonutChart segments={snapshot.categoryMix} size={110}/></div><div style={panel}>{kicker('CEO View')}<h3 style={{margin:'0 0 1.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Portfolio Mix by Industry</h3><DonutChart segments={snapshot.industryMix} size={110}/></div><div style={panel}>{kicker('COO View')}<h3 style={{margin:'0 0 0.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>High-Urgency Advisory Trend</h3><div style={{fontSize:'0.72rem',color:'#94a3b8',marginBottom:'1rem'}}>High and critical outputs per month</div><BarChart data={snapshot.monthlyHighUrgency} color='#ef4444' height={80}/></div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1.25rem',marginBottom:'1.5rem'}}><div style={panel}>{kicker('COO View')}<h3 style={{margin:'0 0 1.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Project Health Mix</h3><DonutChart segments={snapshot.healthMix} size={110}/></div><div style={panel}>{kicker('COO View')}<h3 style={{margin:'0 0 0.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Owner Execution Load</h3><div style={{fontSize:'0.72rem',color:'#94a3b8',marginBottom:'1rem'}}>Top owners by active action count</div><BarChart data={snapshot.ownerLoad.map(item=>({label:item.label.split(' ')[0]||item.label,value:item.value}))} color='#0891b2' height={80}/><div style={{marginTop:'0.9rem',display:'flex',flexDirection:'column',gap:'0.45rem'}}>{snapshot.ownerLoad.map(item=><div key={item.label} style={{display:'flex',justifyContent:'space-between',fontSize:'0.7rem',color:'#94a3b8'}}><span>{item.label}</span><span style={{color:'#e2e8f0',fontWeight:600}}>{item.value}</span></div>)}</div></div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1.25rem',marginBottom:'1.5rem'}}><div style={panel}>{kicker('COO View')}<h3 style={{margin:'0 0 0.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Action Closures by Month</h3><div style={{fontSize:'0.72rem',color:'#94a3b8',marginBottom:'1rem'}}>Completed actions logged per month</div><BarChart data={snapshot.monthlyActionClosures} color='#22c55e' height={80}/></div><div style={panel}>{kicker('COO View')}<h3 style={{margin:'0 0 1.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Execution Backlog Snapshot</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'0.75rem'}}>{[{label:'Open',value:snapshot.openActionsTotal,color:'#60a5fa'},{label:'Completed',value:snapshot.completedActionsTotal,color:'#22c55e'},{label:'Avg Age',value:`${snapshot.avgActionAgeDays}d`,color:snapshot.avgActionAgeDays>14?'#ef4444':'#f59e0b'}].map(item=><div key={item.label} style={{border:'1px solid #1e3a5f',borderRadius:'8px',padding:'0.8rem',background:'rgba(255,255,255,0.02)'}}><div style={{fontSize:'0.65rem',color:'#94a3b8',textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:'0.25rem'}}>{item.label}</div><div style={{fontSize:'1.25rem',fontWeight:700,color:item.color}}>{item.value}</div></div>)}</div></div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1.5fr',gap:'1.25rem'}}><div style={panel}>{kicker('Executive KPIs')}<h3 style={{margin:'0 0 1.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Performance Gauges</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1rem'}}>{gaugeData.map(kpi=><div key={kpi.label} style={{textAlign:'center'}}><GaugeChart value={kpi.value} color={kpi.color}/><div style={{fontSize:'0.68rem',color:'#94a3b8',marginTop:'0.25rem'}}>{kpi.label}</div></div>)}</div></div><div style={panel}>{kicker('Board Scorecard')}<h3 style={{margin:'0 0 1.25rem',fontSize:'0.95rem',fontWeight:'700',color:'#e2e8f0'}}>Executive Performance Summary</h3><div style={{display:'flex',flexDirection:'column',gap:'0.75rem'}}>{scorecardRows.map((row,i)=><div key={i} onMouseEnter={()=>setHoveredCard(`sc-${i}`)} onMouseLeave={()=>setHoveredCard(null)} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0.75rem 1rem',borderRadius:'8px',background:hoveredCard===`sc-${i}`?'rgba(37,99,235,0.08)':'rgba(255,255,255,0.02)',border:'1px solid #1e3a5f'}}><div style={{display:'flex',alignItems:'center',gap:'0.75rem'}}><row.icon size={14} color={row.color}/><div><div style={{fontSize:'0.8rem',fontWeight:'500',color:'#e2e8f0'}}>{row.area}</div><div style={{fontSize:'0.7rem',color:'#94a3b8'}}>{row.value}</div></div></div><span style={{fontSize:'0.65rem',fontWeight:'600',padding:'0.15rem 0.6rem',borderRadius:'999px',background:`${row.color}22`,color:row.color,border:`1px solid ${row.color}44`,whiteSpace:'nowrap'}}>{row.status}</span></div>)}</div></div></div>
  </div></NexusShell>;
}
